const WORDS=[
{d:"to find and bring back",w:"retrieve"},
{d:"the ability to direct the actions of someone or something",w:"control"},
{d:"to grow too big or too old for something",w:"outgrow"},
{d:"satisfied or happy",w:"pleased"},
{d:"to grow or come to be something",w:"become"},
{d:"a large, strong box used for holding things",w:"chest"},
{d:"the state of being dirty or not neat",w:"mess"},
{d:"to tell someone that you will definitely do something",w:"promise"},
{d:"an animal that lives in water and turns into a frog or toad",w:"tadpole"},
{d:"not special or in any way",w:"ordinary"},
{d:"having or showing good sense or judgment",w:"sensible"},
{d:"to bring in or take out in secret",w:"smuggle"},
{d:"excellent and very impressive",w:"splendid"},
{d:"in a manner that shows that you feel that something is wrong or that someone is behaving wrongly",w:"suspiciously"},
{d:"the process by which someone or something is taught skills or how to behave",w:"training"},
{d:"old and often valuable",w:"antique"},
{d:"causing tremendous surprise or wonder; extremely amazing",w:"astounding"},
{d:"the quality of being dutiful or following directions and rules",w:"obedience"},
{d:"to shake slightly",w:"tremble"},
{d:"unhappy, angry, or worried",w:"upset"}
];
